### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Benrise/graduate_work#1]
Здравствуйте ! Отлично поработали ! Оставил небольшие рекомендации:

1. [Тут](https://github.com/Benrise/graduate_work/blob/10b8b345d7b32e114d21b17562bef6d27c6bc12b/services/assistant/docker-entrypoint.sh#L3) я бы рекомендовал запускать как описано тут https://www.uvicorn.org/deployment/#deployment
2. [Тут](https://github.com/Benrise/graduate_work/blob/10b8b345d7b32e114d21b17562bef6d27c6bc12b/services/assistant/main.py#L26-L31) я бы не рекомендовал запускать бекграунд процессы совместно с апи приложением, особенно если они достаточно "тяжелые" (править тут это наверное не нужно, но имейте ввиду - я бы рекомендовал если это нужно, просто сделать маленький отдельный сервис)
3. [Тут](https://github.com/Benrise/graduate_work/blob/10b8b345d7b32e114d21b17562bef6d27c6bc12b/services/assistant/api/v1/search.py#L1-L13) секции импортов в проекте неплохо было бы привести к PEP8 https://peps.python.org/pep-0008/#imports

**Comment by Benrise** [comment]
1. Fixed:
- [Production deployment execution for FastAPI servcies](https://github.com/Benrise/graduate_work/commit/e754138716319eb75d8b9192755ef71e79fb3b4e)
3. Fixed:
- [PEP8 Imports](https://github.com/Benrise/graduate_work/commit/37f2b855fac7a187215ffc984b27502222396be3)
- [Remove isort for correct PEP8](https://github.com/Benrise/graduate_work/commit/a6230d0e08bb3039e3b255eeead7668b7ecced3b)

**Comment by Benrise** [comment]
1. Fixed:
- [Production deployment execution for FastAPI servcies](https://github.com/Benrise/graduate_work/commit/e754138716319eb75d8b9192755ef71e79fb3b4e)
3. Fixed:
- [PEP8 Imports](https://github.com/Benrise/graduate_work/commit/37f2b855fac7a187215ffc984b27502222396be3)
- [Remove isort for correct PEP8](https://github.com/Benrise/graduate_work/commit/a6230d0e08bb3039e3b255eeead7668b7ecced3b)
